title: "Katharine Sadler / K. G. Sadler"
author: "Dean Sadler"
#description: "Made with <b style=\"color: #f45;\">&lt;3</b>"
description: "&copy; Katharine Sadler"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
   - {file: "index.html", title: Home}
#  - {file: "README.md",  title: About}
#  - {file: "blog.md",  title: Blog}
#  - {file: "index.html", title: Home, icon: home}
#  - {file: "README.md",  title: About, icon: address-card}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
   - {title: Mail, icon: envelope, url: "mailto:info@katharinesadler.com"}
#  - {title: Github, icon: github, url: "https://github.com/niklasbuschmann/contrast"}
  - {title: Amazon, icon: amazon, url: "https://amazon.com"}
  - {title: Goodreads, icon: goodreads, url: "https://amazon.com"}
  - {title: facebook, icon: facebook, url: "https://facebook.com"}
  - {title: Twitter, icon: twitter, url: "https://twitter.com"}
  - {title: Pinterest, icon: pinterest, url: "https://pintrest.com"}

# - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
